agent_name: "basic_agent"
description: "A simple agent that responds to basic queries"
framework: "langgraph" 
template: "basic"
version: "0.1.0"
created_at: "2024-01-17 13:42:03"

template_source:
  repo_url: "https://github.com/runagent-dev/runagent.git"
  path: "templates/langgraph/basic"
  author: "radeen"

agent_architecture:
  entrypoints:
    - file: "main.py"
      module: "run"
      type: "generic"

env_vars:
  OPENAI_API_KEY: "sk-proj-1234567890"
